name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # optional, يشغله كل يوم

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✨ لازم تضيف دي عشان يكتب على الفرع
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: AbdelhamidSherif   # ✨ غيرها لليوزر بتاعك
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
